### ISSUE TITLE
Live demo not working with "Internal Server Error" every time

### ISSUE THREAD

**Issue by liangjacky** [chrisdonahue/ddc#13]
Uploade a song, select difficulty, type title and artist, and goes to ISE page every time.

**Comment by chrisdonahue** [comment]
Should be fixed! Thx for reporting.

**Comment by mgintz289** [comment]
Issue has returned!

**Comment by chrisdonahue** [comment]
Thx for the heads up! Unfortunately I no longer have the ability to fix the demo on the original URL. Please use this new URL which should run indefinitely: https://ddc.chrisdonahue.com
