### ISSUE TITLE
Live demo not functioning

### ISSUE THREAD

**Issue by okaybenji** [chrisdonahue/ddc#4]
Completing the live demo form gives either `Internal server error` or `413 Request Entity Too Large`. Note the uploads seem to go through, and the files are all significantly less than the 16 MB limit.

(I would run the demo locally but I can't seem to get that working either. Thanks for your work on this!)

**Comment by chrisdonahue** [comment]
I have fixed the live demo: http://deepx.ucsd.edu/ddc . Should be more stable from now on. Sorry for the delay and thanks for your interest!
