### ISSUE TITLE
unable to find module essentia

### ISSUE THREAD

**Issue by shyamalschandra** [chrisdonahue/ddc#6]
One of the dependencies name essentia is not found by python when running the bash script ddc_server.sh.  I did the following:

`brew install essentia` (that didn't work)
`pip install --user essentia` (that didn't work)
installed essentia from source (that didn't solve the problem)

Do you know what other options that I have in order to get this code work on my High Sierra setup on MacOS?

Thanks!

**Comment by chrisdonahue** [comment]
Looks like you need to use their formula: https://github.com/MTG/homebrew-essentia

Let me know if this doesnt work and I can provide further assistance. Thank you for your interest!

**Comment by shyamalschandra** [comment]
Hi @chrisdonahue,

I executed the commands in that document and still, nothing works for python 2 and 3.
